# Generated by Django 2.2.3 on 2019-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='shortened_url',
            field=models.CharField(max_length=8),
        ),
    ]
