# Generated by Django 2.2.3 on 2019-08-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190731_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='tob',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
