# Generated by Django 2.2.3 on 2019-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190809_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
