# Generated by Django 2.2.3 on 2019-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190811_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='actual_url',
            field=models.URLField(error_messages={'invalid': 'fuck you'}, max_length=2048),
        ),
    ]
