# Generated by Django 2.2.3 on 2019-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190811_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='actual_url',
            field=models.URLField(max_length=2048),
        ),
    ]
