# Generated by Django 2.2.3 on 2019-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190811_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='id',
        ),
        migrations.AlterField(
            model_name='database',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=8, primary_key=True, serialize=False),
        ),
    ]
