# Generated by Django 2.2.3 on 2019-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190811_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=16, primary_key=True, serialize=False),
        ),
    ]
