# Generated by Django 2.2.3 on 2019-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190811_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
