# Generated by Django 2.2.3 on 2019-08-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_database_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='dob',
            new_name='dom',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='tob',
            new_name='tom',
        ),
    ]
